name: Release

on:
  push:
    branches: [master, next]

jobs:
  release:
    name: Release latest version
    runs-on: ubuntu-latest

    steps:
      - uses: python-semantic-release/python-semantic-release@v10.0.2
      - uses: python-semantic-release/publish-action@v10.0.2
